### ISSUE TITLE
惯性

### ISSUE THREAD

**Issue by krmao** [wcy10586/OverscrollLayout#2]
别的都挺完美了，就差一个惯性
我尝试使用behavior 但是没有搞定
就是Listview fling 的边界的时候有一个惯性回弹，
目前的回弹建立在拖拽的基础上，不是fling.
不知楼主有没有方案

另外关于越拉越难拉动的算法
private float getDealt(float dealt, float distance) {
        if (dealt \* distance < 0)
            return dealt;
        //x 为0的时候 y 一直为0, 所以当x==0的时候,给一个0.1的最小值
        float x = (float) Math.min(Math.max(Math.abs(distance), 0.1) / Math.abs(baseOverScrollLength), 1);
        float y = Math.min(new AccelerateInterpolator(0.15f).getInterpolation(x), 1);
        return dealt \* (1 - y);
    }
这个我试过感觉要更好一点

**Comment by wcy10586** [comment]
@mkrcpp   可以通过Gesturedetector 来判断手势 是否为fling ，如果是fling  在Li stview 结束滚动的时候可以做个动画！

**Comment by wcy10586** [comment]
@krmao 已添加添加fling惯性，可以下载最新的lib库

**Comment by krmao** [comment]
@wcy10586  嗯,看到了,待会看看源码,我在你的库的基础上增加了刷新的组件,但是效果不是很好,有精力的话我需要在优化优化,谢谢你.
https://github.com/krmao/MPullLib
