### ISSUE TITLE
你好，ScrollView视图中有轮播图，，会有与轮播图的左右滑动 手势冲突

### ISSUE THREAD

**Issue by LinF2015** [wcy10586/OverscrollLayout#3]

**Comment by wcy10586** [comment]
这个 需要你自己对事件做判断，在轮播图时候的禁止overscroll

**Comment by LinF2015** [comment]
我对手势这块不太熟悉，我在dispatchTouchEvent里加了判断，但还是不行，

**Comment by wcy10586** [comment]
pager.setOnTouchListener(new View.OnTouchListener() {
            @Override
            public boolean onTouch(View v, MotionEvent event) {
                switch (event.getAction()){
                    case MotionEvent.ACTION_DOWN:
                        overScrollLayout.requestDisallowInterceptTouchEvent(true);
                       break;
                    case MotionEvent.ACTION_UP:
                    case MotionEvent.ACTION_CANCEL:
                        overScrollLayout.requestDisallowInterceptTouchEvent(false);
                        break;
                }
                return false;
            }
        });

pager是你需要获取事件的控件。

在 overscrolllayout的disaptchtouchevent方法的第一行 加入这么一段代码： 
       if (disallowIntercept){
            return super.dispatchTouchEvent(ev);
        }

这样就可以很好的控制轮播了

**Comment by LinF2015** [comment]
谢谢你
